### ISSUE TITLE
not a valid json

### ISSUE THREAD

**Issue by Danizu** [XopheLucas/TalkToYourSensor#1]
hello I'm trying to upload in conversation service but at parsing stage it's not a valid json file.

**Comment by XopheLucas** [comment]
Not sure how you got there, but FYI, I just: 
- downloaded the _TalkToYourSensor-WatsonConversation.json_
- created a fresh Watson Conversation Service
- did _Import Workspace_ using the above json, exactly as per Section 4 - Option A of my recipe

**... and all worked fine !**

Can you try again with a 'fresh' Watson Conversation service ?

**Comment by XopheLucas** [comment]
Closed this for now. Re-open if my first comment does not address the Issue.
